"Filed out from Dolphin Smalltalk 7"!

RuntimeSessionManager subclass: #EncuentraloSessionManager
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
EncuentraloSessionManager guid: (GUID fromString: '{1943fd47-167e-479d-abcc-8ad112815b0e}')!
EncuentraloSessionManager comment: ''!
!EncuentraloSessionManager categoriesForClass!Unclassified! !
!EncuentraloSessionManager methodsFor!

main

	Encuentralo new! !
!EncuentraloSessionManager categoriesFor: #main!public! !

